os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "13.2.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - /.*/

before_install:
  - sudo apt-get update

install:
  - npm install -g @angular/cli@next
  #- npm install

jobs:
  include:
    ## Build Stage  ##
    - stage: Build App
      if: branch = development
      script:
      - ng --version
      - ng build

    ## Deploy Stage ##
    - stage: Deploy App
      if: branch = master
      script: ng build --prod


notifications:
  email:
    on_failure: always
    on_success: never
