os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "13.5.0"
  - "12.14.0"


branches:
  only:
    - master
    - development

before_install:
  - sudo apt-get update

install:
  - npm install -g @angular/cli@next

jobs:
  include:
    ## Build Stage  ##
    - stage: Build App
      if: branch = development
      script:
      - ng build --prod

    ## Deploy Stage ##
    - stage: Deploy App
      if: branch = master
      script: ng build --prod


notifications:
  email:
    on_failure: always
    on_success: never
