os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "10.15.3"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - /.*/

before_install:
  - sudo apt-get update

install:
  - npm install -g @angular/cli
  - npm install
  - npm audit fix

jobs:
  include:
    - stage: compile
      name: "ng lint"            # names the first Tests stage job
      script: ng lint
    - script: ng build
      name: "ng build"

    - stage: test
      script: ng test
      name: "ng test"

    - stage: deploy
      script: ng build --prod --base-href https://github.com/pavankjadda/SpringSecurity-SpringData-UI.git


notifications:
  email:
    on_failure: always
    on_success: change
